---
title: "2020 Media Coverage vs. Public Opinion"
author: "Hoda Abdalla"
date: "10/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readxl)
library(data.table)
library(rvest)
library(tidyverse)
```

```{r Reading in Data, warning = FALSE}


download.file("https://raw.githubusercontent.com/fivethirtyeight/data/master/media-mentions-2020/cable_weekly.csv", "./raw-data/cable_mentions.csv", mode = "wb")

cable_mentions <- read_csv("raw-data/cable_mentions.csv", col_types = cols(
  date = col_date(format = ""),
  name = col_character(),
  matched_clips = col_double(),
  all_candidate_clips = col_double(),
  total_clips = col_double(),
  pct_of_all_candidate_clips = col_double(),
  query = col_character()
))



download.file("https://raw.githubusercontent.com/fivethirtyeight/data/master/media-mentions-2020/online_weekly.csv", "./raw-data/online_mentions.csv", mode = "wb")


online_mentions <- read_csv("raw-data/online_mentions.csv", col_types = cols(
  date = col_date(format = ""),
  name = col_character(),
  matched_stories = col_double(),
  all_candidate_stories = col_double(),
  pct_of_all_candidate_stories = col_double(),
  query = col_character()
))


download.file("https://projects.fivethirtyeight.com/polls-page/president_primary_polls.csv", "./raw-data/polling.csv", mode = "wb")

polling <- read_csv("raw-data/polling.csv", col_types = cols(
  .default = col_character(),
  question_id = col_double(),
  poll_id = col_double(),
  cycle = col_double(),
  pollster_id = col_double(),
  sponsor_ids = col_number(),
  pollster_rating_id = col_double(),
  sample_size = col_double(),
  sponsor_candidate = col_logical(),
  internal = col_logical(),
  tracking = col_logical(),
  nationwide_batch = col_logical(),
  notes = col_logical(),
  candidate_id = col_double(),
  pct = col_double()
))

betting <- read_xlsx("raw-data/2020_betting_data.xlsx")
```

```{r}
polling <-
  polling %>%
  mutate(name = answer) %>%
  dplyr::select(name, pct)


betting <- betting %>%
  mutate(name = ContractName) %>%
  dplyr::select(name, Date, OpenSharePrice)

online_mentions <- online_mentions %>%
  mutate(name = sapply(strsplit(name, ' '), function(x) x[length(x)])) %>%
  dplyr::select(name, date, matched_stories) %>%
mutate(month = format(as.Date(date, format="%Y/%m/%d"),"%m")) %>%
   mutate(month = as.integer(month, format = "%m")) %>%
  filter(month == 10)

cable_mentions <- cable_mentions %>% 
  mutate(name = sapply(strsplit(name, ' '), function(x) x[length(x)])) %>%
  dplyr::select(name, date, matched_clips) %>%
  mutate(month = format(as.Date(date, format="%Y/%m/%d"),"%m")) %>%
   mutate(month = as.integer(month, format = "%m")) %>%
  filter(month == 10)

data <- 
  Reduce(function(...) merge(..., all=TRUE), list(online_mentions, cable_mentions, polling, betting)) %>%
   mutate(month = format(as.Date(date, format="%Y/%m/%d"),"%m")) %>%
   mutate(month = as.integer(month, format = "%m")) %>%
  filter(month == 10) %>%
  group_by(name) %>%
  summarise(percent = mean(pct, na.rm = TRUE), stories = mean(matched_stories, na.rm = TRUE), clips = mean(matched_clips, na.rm = TRUE), price = mean(OpenSharePrice, na.rm = TRUE))

write_rds(data, path = "raw-data/data.rds")



```


